version: '3.8'

services:
  # 1. Локальная База Данных (с поддержкой векторов)
  db:
    image: ankane/pgvector:v0.5.1
    container_name: ailawyer_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: ailawyer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Redis
  redis:
    image: redis:7-alpine
    container_name: ailawyer_redis
    ports:
      - "6379:6379"

  # 3. Backend
  backend:
    build: ./backend
    container_name: ailawyer_backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - media_data:/app/uploads
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - UPLOAD_DIR=/app/uploads
      # Ссылка на локальную базу (имя хоста 'db')
      - DATABASE_URL=postgresql+psycopg2://admin:adminpassword@db:5432/ailawyer_db
    env_file:
      - .env
    depends_on:
      - redis
      - db

  # 4. Worker
  worker:
    build: ./backend
    container_name: ailawyer_worker
    command: celery -A celery_app worker --loglevel=info
    volumes:
      - ./backend:/app
      - media_data:/app/uploads
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - UPLOAD_DIR=/app/uploads
      - C_FORCE_ROOT=true
      - DATABASE_URL=postgresql+psycopg2://admin:adminpassword@db:5432/ailawyer_db
    env_file:
      - .env
    depends_on:
      - redis
      - backend
      - db

  # 5. Frontend
  frontend:
    build: ./frontend
    container_name: ailawyer_frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

volumes:
  media_data:
  postgres_data: